name: release-please

on:
  push:
    branches:
      - release
      - develop
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref to deploy (e.g. main, v1.0.0, c91ee3c, etc.)'
        required: true
permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: use-release-please
          default-branch: main
